### ISSUE TITLE
Apply to Job Page

### ISSUE THREAD

**Issue by albie0019** [2023Seng371Team7/Hiring-Registration-System#47]
Create UI for Apply to Job Page
(Logic to be dealt with in a separate issue)

**Comment by brennanwilkes** [comment]
This is one of our main blockers for submission right @albie0019? @lydialulie how is progress?

**Comment by albie0019** [comment]
@brennanwilkes I'm working on a separate issue atm (#100 View Applicants Page). After I finish that, I can see how I can help Lydia with this.

**Comment by lydialulie** [comment]
I am working on it right now and Albie is helping.

**Comment by brennanwilkes** [comment]
👍🏻👍🏻
